name: pincerprojects
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - numpy
  - pandas
  - pip
  - python=3.11
  - spyder-kernels>=2.4
  - yaml
  - pip:
      - pyabf