name: pincerenv
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - numpy
  - openpyxl
  - pandas
  - pip
  - python=3.11
  - spyder-kernels>=2.4
  - scipy
  - yaml
  - pip:
      - pyabf